### PR TITLE
Ability to log all requests and responses from edge service when --diagnostics option is passed. 

### PR DESCRIPTION
**Pull request by nojvek**
Also adding short names to yargs

### CODE REVIEW

**Comment by auchenberg** [comment]
👍

**Comment by roblourens** [comment]
@nojvek From personal experience you'll want to write to a file. The vscode console is not great for this since you can't easily copy large amounts of text out. Might be a good time to create a centralized class for this which would also let you make just a single `if (this._diagLogging) {` check.

**Comment by nojvek** [comment]
Good point, I'll borrow what you did in vscode-debug-core

**Comment by roblourens** [comment]
There might even be some npm module that does a better job. I never got around to looking.

**Comment by roblourens** [comment]
And some of my code is specific to a vscode debug adapter.

**Pull request merged**
