### PR TITLE
Add Visual C++ Redistributable and postinstall script

### PR DESCRIPTION
**Pull request by sarvaje**
The network proxy needs the redistributable to be present in the computer.
This PR adds a post install script to install them.
Also I have modified the package.json to allow just to be installed in a computer with windows.

### CODE REVIEW

**Comment by sarvaje** [comment]
I have also updated the file `protocol.json` to support the domain Network and added the method `getOuterHTML` in the `DOM` domain

**Comment by molant** [comment]
@sarvaje the PR is failing probably because of the postinstall script. Can you update `.travis.yml` with the following lines:

```yml
install:
- npm install --ignore-scripts
```

Hopefully that should fix the issue.

Thanks!

**Comment by sarvaje** [comment]
@molant the problem now is that I have added this to the `package.json`
```json
"os": [
     "win32"
 ]
```
because the network protocol will work just in windows

Should I remove this condition?

**Comment by molant** [comment]
Let's remove the condition for now.
@andysterland, @auchenberg maybe we should configure appveyor in this repo to build on Windows in favor of Travis?
Happy to look into it if you give me the permissions :)

**Pull request merged**
